language: go

go:
  - "1.x"
  - "1.9.x"
  - "1.10.x"
  - master

matrix:
  allow_failures:
    - go: master

go_import_path: cryptoscope.co/go/secretstream

install:
  - go get -t -v cryptoscope.co/go/secretstream/...
